steps:
- name: 'gcr.io/cloud-builders/git'
  args:
    - clone
    - '--depth=1'
    - 'https://github.com/devopsgcp/gcp-cicd-microservice.git'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'src/adservice/Dockerfile', '-t', 'us-central1-docker.pkg.dev/cicd-2024/ecommerce/adservice:v1', '.']
