steps:
#Step 0: cloning source code from github
- name: 'gcr.io/cloud-builders/git'
  args:
    - clone
    - '--depth=1'
    - 'https://github.com/devopsgcp/gcp-cicd-microservice.git'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud builds submit --config=src/adservice/cloudbuild.yaml

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud builds submit --config=src/checkoutservice/cloudbuild.yaml

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud builds submit --config=src/currencyservice/cloudbuild.yaml

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud builds submit --config=src/emailservice/cloudbuild.yaml

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud builds submit --config=src/frontend/cloudbuild.yaml

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud builds submit --config=src/loadgenerator/cloudbuild.yaml

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud builds submit --config=src/paymentservice/cloudbuild.yaml

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud builds submit --config=src/productcatalogservice/cloudbuild.yaml

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud builds submit --config=src/recommendationservice/cloudbuild.yaml

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud builds submit --config=src/shippingservice/cloudbuild.yaml

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud builds submit --config=src/shoppingassistantservice/cloudbuild.yaml

# Deploy on Gke cluster

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'configure-kubectl'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - 'ecommerece'
    - '--region'
    - 'us-central1'
    - '--project'
    - 'cicd-2024'

  # Step 3: Deploy the pod to the GKE cluster
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'deploy-pod'
  args:
    - 'apply'
    - '-f'
    - 'kubernetes-spec'


# gcloud container clusters get-credentials ecommerece --region us-central1 --project cicd-2024
