steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'productcatalogservice'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if gcloud artifacts docker images list \
        us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce/productcatalogservice \
        --filter="tags:v1" --format="json" | grep -q '"v1"'; then
        echo "Images already exists.. skipping build."
        exit 0
      fi 

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'src/productcatalogservice/Dockerfile', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce/productcatalogservice:v1', '.']


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce/productcatalogservice:v1']