steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'emailservice'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if gcloud artifacts docker images list \
        us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce/emailservice \
        --filter="tags:v1" --format="json" | grep -q '"v1"'; then
        echo "Images already exists.. skipping build."
        exit 0
      fi

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'src/emailservice/Dockerfile', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce/emailservice:v1', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/ecommerce/emailservice:v1']